# Generated by Django 3.2.19 on 2023-05-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prince',
            new_name='price',
        ),
    ]
